### PR TITLE
Support Alexa v3

### LINKED ISSUE #19: Cannot read property 'namespace' of undefined at exports.handler (/var/task/index.js:10:25)
This is the error I get when attempting to enable the skill for Alexa. I'm not sure where to go from here with this? (I'm not a programmer by any means...) I think I have the rest of it setup correctly, I've been through your wiki 3 times now and can't find anything I did incorrectly, so I'm at a loss for what to do next.

Thanks!

### PR DESCRIPTION
**Pull request by barwin**
First off, thank you for putting this project together and for writing such great setup instructions!

While initially trying it out, I ran into the v2/v3 upgrade issue (as others have) and decided to dig in. Here is a summary of the changes included in this p/r:

- Support Alexa v3
- Added a lot of tests with sample payloads and responses.  I opted for jest since it's an all-in-one test framework, but I'm happy to use a different one if you're not a fan.
- Move auth to separate `iComfort.js` file for easier sharing between code and tests. (Only have to hard-code user information once)
- Support `DEBUG` Lambda environment variable for extra logging.
- No longer need to send Celsius to Alexa, because we can specify Fahrenheit in the response (Alexa will still speak in Celsius to those who have chosen that preference for their Alexa device).
- Deny requests while in Away mode.
- Deny requests that are out-of-range (allowed range is between 60-99F)

Let me know if you have any feedback or concerns about these changes. I'm happy to tweak as necessary.

I am currently using this version of the module with my home system, and it seems to be working well.  But I would very much appreciate feedback if there are opportunities to improve here.

-Ben

Fixes #19

### CODE REVIEW

**Comment by kate-hall** [comment]
This is amazing!! Thank you @barwin, I'm going to test on my own system tonight and merge straight away if it works.

**Comment by cmarkovitz** [comment]
@kate-hall have you updated the branch to work with v3?

**Comment by barwin** [comment]
@cmarkovitz - If you're up for it, you could use my [v3_upgrade](https://github.com/barwin/alexa-icomfort/tree/barwin/v3_upgrade) branch and install off of that. There are a lot of changes in this p/r so having a few people test it wouldn't be a bad idea before @kate-hall has a chance to review/test/merge. 

To test my branch directly, first clone my fork of the repo, then checkout `v3_upgrade` and then follow Kate's instructions from there:
- `git clone https://github.com/barwin/alexa-icomfort.git`
- `cd alexa-icomfort`
- `git checkout -t origin/barwin/v3_upgrade`
- Follow normal setup instructions from here

-Ben

**Comment by kate-hall** [comment]
@barwin, thanks so much again (and sorry I'm so slow!) So far everything's working great in my trial run, I rewrote the Wiki instructions to match the new setup and will merge, then take a look at how this matches up with some of the new functions I'd been writing.

I extra appreciate the jest tests, testing is not my forte and this is a good kick in the pants to learn more!

**Comment by barwin** [comment]
Thanks for the merge @kate-hall :)  Glad to hear it's working for you as well.   Thanks again for a great project.

**Comment by cmarkovitz** [comment]
@kate-hall @barwin going to test it out now.  Thanks to both of you for the effort.

**Comment by cmarkovitz** [comment]
@kate-hall @barwin  I am happy to report that it is working.  It also found my 2 zones with no problem.  The odd thing is that it is showing I have them set to COOL / HEAT when they are cool only and when I asked to change the temperature - even though it worked - it told me they are set to keep the temperature between X and Y degrees.

**Pull request merged**
